### PR TITLE
Changed the way that the crypto transformers are created

### PR DESCRIPTION
**Pull request by hermanocabral**
Hey, my first pull request here! Hope I'm not doing anything wrong...

I was having very poor performance creating the crypt/decrypt transformers on every Encode/Decode call, so I changed the way they are created and that seemed to do the trick.

Would it be worth to pull this to your repo? Maybe it's going to be useful since there is a link to your blog post in the RavenDB mailing list.

### CODE REVIEW

**Comment by daniellangnet** [comment]
Thanks for contributing that!

**Comment by hermanocabral** [comment]
No problem! It would be nice to put a disclaimer that the code is just an
example, in real world usage the encryption code would need some tweak to
test if the transformers can be reused and stuff..

On Sat, Jan 28, 2012 at 1:30 PM, Daniel Lang <
reply@reply.github.com

**Comment by daniellangnet** [comment]
Don't know if that's necessary since it should be very clear, that this is just for demonstration purposes of how you _can_ do document encoding, just above the storage engines. I "real world usage" you would probably want to have a stronger key (e.g. a pkc file) that is certainly not stored as plain text within the source-code. Also note, that we have not salting on a document basis here - that is something you definitely want to have.

**Comment by hermanocabral** [comment]
Yes, you're probably right. On aside note, have you ever used RavenDB with
encryption? Do you know how it behaves in terms of indexes speed and stuff?

On Sat, Jan 28, 2012 at 1:39 PM, Daniel Lang <
reply@reply.github.com

**Comment by daniellangnet** [comment]
No, I haven't used it in a real-world project. However, I know some parts of ravens source code and also how the AbstractDocumentCodec is used. Since it's purpose is to enable a very solid encryption/encoding and thus is used very deep in the rabbit hole, it has significant impact on performance, especially on indexes. As the map function will run on every new or changed document, encryption will slow down indexing.

In the end, the overall peformance hit will depend on the usage of RavenDB. If you like, you can send me an email oultining your concrete scenario and see if we can optimize that.

**Pull request merged**
